#ifndef ConfigureAnalogInputDialogWellerToJBC
#define ConfigureAnalogInputDialogWellerToJBC

void Windows_Dialogs_ConfigurationDialogs_ConfigurationWellerToJBC_ConfigureAnalogInputDialog_showConfigureAnalogInputDialog(bool* configureAnalogInput);

#endif // !ConfigureAnalogInputDialogWellerToJBC
