#ifndef DatabaseConnectionDialog
#define DatabaseConnectionDialog

void Windows_Dialogs_ConnectionDialogs_DatabaseConnectionDialog_showDatabaseConnectionDialog(bool* selectDatabaseServer);

#endif DatabaseConnectionDialog