#ifndef ConfigureMeasurementDialog
#define ConfigureMeasurementDialog

void Windows_Dialogs_MeasurementDialogs_ConfigureMeasurementDialog_showConfigureMeasurementDialog(bool* configureMeasurement);

#endif // !ConfigureMeasurementDialog
