#ifndef LogFilePathDialog
#define LogFilePathDialog

bool Windows_Dialogs_FileDialogs_LogFilePathDialog_showSelectFileDialog(bool* selectFile);
bool Windows_Dialogs_FileDialogs_LogFilePathDialog_showCreateFileDialog(bool* createFile);
bool Windows_Dialogs_FileDialogs_LogFilePathDialog_showDeleteFileDialog(bool* deleteFileDialog);

#endif // !LogFilePathDialog
