#ifndef ConfigureAnalogInputDialogSTM32PLC
#define ConfigureAnalogInputDialogSTM32PLC

void Windows_Dialogs_ConfigurationDialogs_ConfigurationSTM32PLC_ConfigureAnalogInputDialog_showConfigureAnalogInputDialog(bool* configureAnalogInput);

#endif // !ConfigureAnalogInputDialogSTM32PLC
