#ifndef ConfigureCANopenUSBportDialog
#define ConfigureCANopenUSBportDialog

void Windows_Dialogs_ConfigurationiDialogs_ConfigurationCANopen_ConfigureCANopenUSBportDialog_showConfigureDialog(bool* configureCANopenUSBportDialog);

#endif // !ConfigureCANopenUSBportDialog