#ifndef ConfigureCANopenDialog
#define ConfigureCANopenDialog

void Windows_Dialogs_ConfigurationiDialogs_ConfigurationCANopen_ConfigureCANopenDialog_showConfigureDialog(bool* configureCANopenDialog);

#endif // !ConfigureCANopenDialog