#ifndef ConfigureSAEJ1939Dialog
#define ConfigureSAEJ1939Dialog

void Windows_Dialogs_ConfigurationiDialogs_ConfigurationSAEJ1939_ConfigureIdentificationsDialog_showConfigureIdentificationsDialog(bool* configureSAEJ1939Identifications);

#endif // !ConfigureSAEJ1939Dialog

